WASI_SDK   := $(shell pwd)/../deps/wasi-sdk
EMSCRIPTEN ?= $(shell dirname "$$(command -v emcc)")
LIBRETRO   := $(shell pwd)/../deps/libretro-common

ifeq ($(EMSCRIPTEN),.)
$(error emcc was not found. Install/activate emsdk or pass EMSCRIPTEN=/path/to/emscripten)
endif

MAKEFLAGS += --no-print-directory
QUIET := > /dev/null 2>&1

DEFINES += \
	--sysroot=$(WASI_SDK)/share/wasi-sysroot \
	--target=wasm32-wasi-threads -pthread -D_WASI_EMULATED_MMAN -mllvm -wasm-enable-sjlj \
	-I$(shell pwd)/../deps/zlib

ifeq ($(DEBUG), 1)
DEFINES += -O0 -ferror-limit=0 -DDEBUG
LDFLAGS += -O0 -g -Wl,--error-limit=0
else
DEFINES += -O3
LDFLAGS += -O3
endif

CC     := $(WASI_SDK)/bin/clang $(DEFINES)
CXX    := $(WASI_SDK)/bin/clang++ $(DEFINES)
AR     := $(WASI_SDK)/bin/ar
RANLIB := $(WASI_SDK)/bin/ranlib
